# Generated by Django 2.0.1 on 2018-05-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadbuilder_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseImageEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='./usercontent/')),
                ('processing_complete', models.BooleanField(default=False)),
                ('processing_started', models.BooleanField(default=False)),
            ],
        ),
    ]
