# Generated by Django 2.0.1 on 2018-07-19 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import loomit_server.storage_backends
import threadbuilder_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threadbuilder_app', '0002_baseimageentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseimageentry',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseimageentry',
            name='image',
            field=models.ImageField(storage=loomit_server.storage_backends.MediaStorage(), upload_to=threadbuilder_app.models.img_upload_to),
        ),
    ]
