# Generated by Django 2.0.1 on 2018-07-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadbuilder_app', '0003_auto_20180718_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseimageentry',
            name='bottomRightX',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseimageentry',
            name='bottomRightY',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseimageentry',
            name='topLeftX',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseimageentry',
            name='topLeftY',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseimageentry',
            name='zoom',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
