# Generated by Django 2.0.1 on 2018-07-30 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threadbuilder_app', '0004_auto_20180729_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseimageentry',
            old_name='bottomRightX',
            new_name='bottom_right_x',
        ),
        migrations.RenameField(
            model_name='baseimageentry',
            old_name='bottomRightY',
            new_name='bottom_right_y',
        ),
        migrations.RenameField(
            model_name='baseimageentry',
            old_name='topLeftX',
            new_name='top_left_x',
        ),
        migrations.RenameField(
            model_name='baseimageentry',
            old_name='topLeftY',
            new_name='top_left_y',
        ),
    ]
